services:
  dbservice:
    image: mysql
    container_name: jobportaldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobportal
    volumes:
      - D:\JAVA PROJECTS\SPRINGPROJECTS\JOB_PORTAL_2\database:/var/lib/mysql